### ISSUE TITLE
请问下怎么注册全局变量。加载静态文件目录

### ISSUE THREAD

**Issue by coolf** [625250353/think-twig#2]
请问下怎么注册全局变量。加载静态文件目录

**Comment by rain-sjh** [comment]
你可以直接在common.php写一个方法,也可以把TwigExpand.php文件放到extend里面,在里面写twig拓展函数,request()在模板里可以直接用的全局数据可以直接放到request或者使用中间件返回给模板







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ruchang"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 上午10:53
收件人: "rain-sjh/think-twig"<think-twig@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [rain-sjh/think-twig] 请问下怎么注册全局变量。加载静态文件目录 (#2)





 
请问下怎么注册全局变量。加载静态文件目录

**Comment by coolf** [comment]
`    'tpl_replace_string' => [
        '__CSS__' => '/static/admin/css',
        '__JS__' => '/static/admin/js',
        '__IMG__' => '/static/admin/images',
    ]`
还是没弄成。。 有没有twig 加载静态文件的例子

**Comment by rain-sjh** [comment]
上两张截图有啊,看不到截图吗.

/**
 * 函数 拓展.
 * @return TwigFunction[]
 */
public function getFunctions()
{
    return [
        new TwigFunction('css', [$this, 'load'], ['is_safe' =&gt; ['all']]),
        new TwigFunction('js', [$this, 'load'], ['is_safe' =&gt; ['all']]),
        new TwigFunction('load', [$this, 'load'], ['is_safe' =&gt; ['all']]),
    ];
}
public function load(...$paths): string
{
    $path = '';
    foreach ($paths as $item) {
        $file_info = pathinfo($item);
        if ($file_info['extension'] === 'css') {
            $path .= "<link href=\"/static/{$item}\" rel=\"stylesheet\" type=\"text/css\"&gt;";
        } elseif ($file_info['extension'] === 'js') {
            $path .= "<script src=\"/static/{$item}\"&gt;</script&gt;";
        } else {
            $path .= "/static/{$item}";
        }
    }

    return $path;
}
<head&gt;
    <meta charset="UTF-8"&gt;
    <title&gt;{{ title|default() }}</title&gt;
    {{ css(
        request().currentTheme.file|default('bootstrap/css/bootstrap.min.css'),
        'fontawesome/css/all.min.css',
        'raindrop/css/app.css'
    ) }}

    {{ js(
        'jquery/jquery-3.5.1.min.js',
        'jquery/expand.js',
        'jquery/jquery.pjax.js',
        'fontawesome/js/all.min.js',
        'bootstrap/js/bootstrap.bundle.min.js',
        'wangEditor/wangEditor.min.js'
    ) }}

</head&gt;





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ruchang"<notifications@github.com&gt;; 
发送时间: 2020年9月7日(星期一) 中午11:24
收件人: "rain-sjh/think-twig"<think-twig@noreply.github.com&gt;; 
抄送: "孙"<625250353@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [rain-sjh/think-twig] 请问下怎么注册全局变量。加载静态文件目录 (#2)





 
    'tpl_replace_string' =&gt; [ '__CSS__' =&gt; '/static/admin/css', '__JS__' =&gt; '/static/admin/js', '__IMG__' =&gt; '/static/admin/images', ]
 还是没弄成。。 有没有twig 加载静态文件的例子

**Comment by coolf** [comment]
感谢，可以了。
是。上面图片看不到
